name: 'Chromatic Deployment'

on:
  push:
    branches:
      - main
      - develop
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # 프로젝트 Node.js 버전 확인 후 수정

      - name: Check package-lock.json
        run: ls -al package-lock.json || echo "package-lock.json not found"

      - name: Install dependencies
        run: npm install  # npm ci 대신 npm install 사용

      - name: Publish to Chromatic
        run: npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }}
